apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spegel

resources:
  - namespace.yaml
  - httproute.yaml
  - cnp

helmCharts:
  - repo: oci://ghcr.io/spegel-org/helm-charts
    name: spegel
    releaseName: spegel
    namespace: spegel
    version: 0.5.1
    valuesFile: values.yaml
