apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
  - repo: https://helm.cilium.io/
    name: cilium
    namespace: kube-system
    releaseName: cilium
    includeCRDs: true
    version: 1.18.5
    valuesFile: values.yaml

resources:
  - gateway.yaml
  - httproute.yaml
  - service.yaml
