apiVersion: v1
kind: Service
metadata:
  labels:
    gateway.networking.k8s.io/gateway-name: cilium
    io.cilium.gateway/owning-gateway: cilium
  name: cilium-gateway-cilium
  namespace: kube-system
spec:
  ports:
  - name: port-80
    nodePort: 32080
    port: 80
    protocol: TCP
    targetPort: 80
  - name: port-443
    nodePort: 32443
    port: 443
    protocol: TCP
    targetPort: 443
  sessionAffinity: None
  type: LoadBalancer
